### ISSUE TITLE
Unable to view specific racer stats

### ISSUE THREAD

**Issue by Anastasia-Romanov** [Try2Win4Glory/Lacan-NTSport#50]
Lacan returns information for the wrong account when attempting to view [505338178287173642](https://www.nitrotype.com/racer/505338178287173642)'s racer profile.  It incorrectly returns the profile of [theteamracer](https://www.nitrotype.com/racer/theteamracer) instead.

**Comment by Try2Win4Glory** [comment]
Hey Anastasia-Romanov,

Thanks for your feeedback! This is due to the bot's ability to view the stats of discord users as well. Could you possibly please provide a potential solution for this problem?

Thanks,
Try2Win4Glory

**Comment by Anastasia-Romanov** [comment]
> Hey Anastasia-Romanov,
> 
> Thanks for your feeedback! This is due to the bot's ability to view the stats of discord users as well. Could you possibly please provide a potential solution for this problem?
> 
> Thanks, Try2Win4Glory

Switch to slash commands.  However, if you're not willing to do that (or too incompetent to do so), adding some sort of flag that users are able to append to the command to change the output would, just barely, suffice.
